name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
    
    - name: Use Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Run test suite
      run: npm test
